### ISSUE TITLE
To be adapted

### ISSUE THREAD

**Issue by giadarol** [PyCOMPLETE/LHC_followup_analysis_scripts#2]
- [x] 002b_bar_plot_per_sector_multiple_fills.py
- [x] 003a_plot_fbct_traces.py
- [x] 004_plot_bunch_lengths.py
- [x] 005_plot_bsrt.py
- [x] 005z_get_BSRT_calib.py
   - but issue with nxcals (see [issue](https://github.com/PyCOMPLETE/LHCMeasurementTools/issues/10))
- [x] 006_plot_stable_phases.py
   - issue with pytimber (see [issue](https://github.com/PyCOMPLETE/LHCMeasurementTools/issues/11))
- [x] 016a_heat_load_period.py
- [x] 016b_heat_load_vs_intensity.py
- [x] 016_heat_load_arcs_vs_SAMs.py

**Comment by kparasch** [comment]
stable phase works as of #3
